#My Properties File
#Tue Mar 03 22:36:05 IST 2026
BASE_URI=http\://64.227.160.186\:9000/v1
Env=qa
Java\ Version=21.0.3
Operating\ System=10.0
Operating\ System\ Version=Windows 11
Project\ Name=Phoenix Test Automation Framework
